apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-wisecow-net-block-http
  namespace: wisecow
spec:
  severity: 8
  message: "Block outbound HTTP(S) from wisecow; allow DNS and app listen port"
  selector:
    matchLabels:
      app: wisecow

  network:
  - matchProtocols:
    - protocol: tcp
    action: Block

  - matchProtocols:
    - protocol: tcp
      port: 4499
    action: Allow

  - matchProtocols:
    - protocol: udp
      port: 53
    action: Allow
