apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-wisecow-block-file-writes
  namespace: wisecow
spec:
  severity: 9
  message: "Block writes to sensitive files and system bin directories from wisecow"
  selector:
    matchLabels:
      app: wisecow

  file:
    matchPaths:
    - path: /etc/shadow
    - path: /etc/passwd
    matchDirectories:
    - dir: /usr/bin/
      recursive: false
    - dir: /sbin/
      recursive: false
    - dir: /usr/sbin/
      recursive: false

  action: Block
