apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-wisecow-block-tools-write
  namespace: wisecow
spec:
  severity: 9
  message: "Block package managers, downloaders and writes to sensitive system files for wisecow"
  selector:
    matchLabels:
      app: wisecow

  process:
  - matchPaths:
    - path: /usr/bin/apt
    - path: /usr/bin/apt-get
    - path: /usr/bin/wget
    - path: /usr/bin/curl
    - path: /usr/bin/python3
    - path: /usr/bin/pip
    action: Block

  - matchPaths:
    - path: /bin/bash
    action: Block

  file:
  - matchPaths:
    - path: /etc/shadow
    - path: /etc/passwd
    action: Block
  - matchDirectories:
    - dir: /usr/bin
      recursive: false
    - dir: /sbin
      recursive: false
    - dir: /usr/sbin
      recursive: false
    action: Block
